### PR TITLE
Write compatibility of KIP Cal0, Serial of the Console in the name of the prodinfo backup, offer reboot on install, include verify in the restore function

### PR DESCRIPTION
**Pull request by Kronos2308**

### CODE REVIEW

**Comment by designgears** [comment]
This doesn't create the flags directory if it doesn't exist and keeps the app from working properly.

**Comment by Kronos2308** [comment]
> This doesn't create the flags directory if it doesn't exist and keeps the app from working properly.

true thaks , now is ok

**Comment by designgears** [comment]
lol, finally gave up

**Comment by Kronos2308** [comment]
I guess a just forgot to close this

**Comment by Kronos2308** [comment]
But the backup on the console nand muust be considered

**Pull request closed without merging**
