### PR TITLE
reboot  funtion

### PR DESCRIPTION
**Pull request by Kronos2308**

### CODE REVIEW

**Comment by ThatNerdyPikachu** [comment]
lol

1. libnx has a bpc impl already
2. You don’t need a class lol, just run the commands...

**Comment by Kronos2308** [comment]
Thanks i will check that

**Comment by Kronos2308** [comment]
Ohh much beter

**Comment by ThatNerdyPikachu** [comment]
You didn’t change anything?

**Comment by Kronos2308** [comment]
Is in private XD

**Comment by Kronos2308** [comment]
This is an old pull request

**Comment by Kronos2308** [comment]
But thanks for the correction

**Pull request closed without merging**
